services:
  # --- INFRASTRUCTURE ---
  postgres:
    image: postgres:18.2-alpine3.22
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_net

  redis:
    image: redis:8.4.0-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - backend_net

  dynamodb:
    image: amazon/dynamodb-local:3.3.0
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    networks:
      - backend_net

  # --- IDENTITY PROVIDER ---
  keycloak:
    image: keycloak/keycloak:26.5
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/quiz-realm.json:/opt/keycloak/data/import/quiz-realm.json:ro
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - backend_net

  # --- BACKEND SERVICES ---
  quiz-service:
    build: ./backend/quiz_service
    container_name: quiz_service
    ports:
      - "8001:8001"
      - "50051:50051"
    environment:
      IS_LOCAL: "true"
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: quiz
      KEYCLOAK_CLIENT_ID: account
    depends_on:
      dynamodb: 
        condition: service_started
      keycloak:
        condition: service_started
    networks:
      - backend_net

  game-service:
    build: ./backend/game_service
    environment:
      IS_LOCAL: "true"
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: quiz
      KEYCLOAK_CLIENT_ID: account
    depends_on:
      redis: 
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - backend_net
    deploy:
      replicas: 3

  nginx-lb:
    image: nginx:alpine3.23
    container_name: nginx_lb
    ports:
      - "8082:8082"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - game-service
    networks:
      - backend_net

  # --- FRONTEND ---
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - quiz-service
      - game-service
    networks:
      - backend_net
    
networks:
  backend_net:
    driver: bridge

volumes:
  redis_data:
  keycloak_db_data: